version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
- cmd: choco install codecov # Can be changed to dotnet tool install --global Codecov.Tool
build:
  verbosity: minimal
test_script:
- cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[*.Test]*  /p:Threshold=10 /p:ThresholdType=line
after_test:
- cmd: codecov -f .\src\pioneer.test\coverage.opencover.xml