version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=10 /p:ThresholdType=line
after_test:
- cmd: curl -s https://codecov.io/bash | bash -s -- -c -F aFlag -f c:\projects\pioneer\src\pioneer.test\coverage.opencover.xml